jobs:
  include:
    - language: c
      os:
        - linux
        - osx
        - freebsd
        - windows
      arch: amd64
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
